Homework 6
0Lyova0/robot-dreams pull request #4
Opened 2023-03-27 18:02 UTC by 0Lyova0

Hi!

Home work 6 done.

2023-04-01 11:29 UTC, acman requested changes
Almost there, several changes should be submitted

2023-04-01 11:29 UTC, acman commented on HW6/task_1_2.py
> +def add_numbers2(a=2, b=5):
task is to path any number of arguments, `*args` should be used there

2023-04-09 14:31 UTC, 0Lyova0 commented
Hi!

changes are made

2023-04-10 14:11 UTC, acman approved these changes
👍

2023-04-10 14:11 UTC, acman commented on HW6/task_1_2.py
> +# I don't know how to_do 2 ** 0.5
The first function was ok. My comment was addressed only to the second task

2023-04-10 14:14 UTC, merged